

[[tasks.precommit]]
name     = "validate"
version  = "0.1"                # <str>
doc      = ["Validate a commit message"]
cli      = [{ name="msgfile",   default="", type="str", positional=true }]
ctor     = "task"               # <str>
actions  = [
         {do="read", from_="msgfile", update_="text"},
         {do="taskcode.precommit:validate", from_="text"}
]

[[tasks.bib]]
name          = "precommit.format"
ctor          = "job"
mixins        = ["job:expander"]
cli           = [{ name="files",   type="list", default=[], positional=true }]
print_levels  = { head="INFO", build="DEBUG", execute="INFO", sleep="WARNING", action="WARNING" }
retriever     = "doot.utils.retrievers:cli_retriever"
exts          = [".bib"]
sub_task      = "bib::_formatter"
